# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

 
#######################################################################################
# Book settings
title                       : Energy Efficiency Shipping  # The title of the book. Will be placed in the left navbar.
author                      : Wengang Mao  # The author of the book
copyright                   : "2021-2022"  # Copyright year to be placed in the footer
logo                        : "contents/images/voysmart.png"  # A path to the book logo
email                       : "wengang.mao@chalmers.se"
exclude_patterns            : ["LICENSE.md"]  # Patterns to skip when building the book. Can be glob-style (for example "*skip.ipynb")

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "off"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
#  exclude_patterns          : ["LICENSE.md"]  # A list of patterns to *skip* in execution (for example a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "contents/images/voysmart_favicon.png"  # A path to a favicon image
  navbar_number_sections    : False  # Add a number to each section in your left navbar
#  google_analytics_id       : "UA-167881009-1"  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  use_repository_button     : true  # Whether to add an "Repository" button to pages. If `true`, repository information in repository: must be filled in
  use_issues_button         : true # Whether to add an "Open issue" button to pages. If `true`, repository information in repository: must be filled in
  use_edit_page_button      : true  # Whether to add an "Suggest edit" button to pages. If `true`, repository information in repository: must be filled in#
  baseurl                   : "https://voysmart.eu"  # The base URL where your book will be hosted. Used for creating image previews and social links. for example: https://mypage.com/mybook/
  extra_navbar              : Visit our <a href="https://github.com/wengangmao/voysmart">GitHub Repository</a>
    <div>This book is powered by <a href="https://jupyterbook.org">Jupyter Book</a></div>
  comments:
    hypothesis: true


#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : "classic"  # The interface interactive links will activate ["classic", "jupyterlab"]
#  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (for example, https://mybinder.org)
  jupyterhub_url            : "https://wengangmao.github.io/voysmart/"  # The URL of the JupyterHub (for example, https://datahub.berkeley.edu)
  thebelab                  : false  # Add a thebelab button to pages (requires the repository to run on Binder)

repository:
  url                       : https://github.com/wengangmao/voysmart  # The URL to your book's repository
  path_to_book              : "./"  # A path to your book's folder, relative to the repository root.

#######################################################################################
theme: jekyll-theme-dinky